#PRACTICA 1 MANEJO E IMPLEMENTACION DE ARCHIVOS alter 
/*
juandiego alvarado salguero papu
*/
/*
ESTE SQL SERA UNICAMENTE PARA LA CREACIION Y LLENAR LAS TABLAS 
LAS CREO Y LAS LLENO EN EL ORDEN QUE YO CREO NESCESARIO PORQUE HAY QUE TENER CUIDADO
CON LAS LLAVES FORANEAS SINO EFAZO :v
*/
/* PRIMER INSERT TABLA HOSPITAL_COVID*/
USE Practica_MIA;
CREATE TABLE HOSPITAL_COVID ( ID_HOSPITAL INT AUTO_INCREMENT, NOMBRE__HOSPITAL VARCHAR(200),
 DIRECCION__HOSPITAL VARCHAR(200) ,
 PRIMARY KEY (ID_HOSPITAL)
 );
 INSERT INTO HOSPITAL_COVID (NOMBRE__HOSPITAL,DIRECCION__HOSPITAL)
 SELECT DISTINCT TemporalR1.NOMBRE_HOSPITAL,TemporalR1.DIRECCION_HOSPITAL
 FROM TemporalR1
 WHERE TemporalR1.NOMBRE_HOSPITAL !="" AND TemporalR1.DIRECCION_HOSPITAL!="";
 /*Tratamiento Aplicado*/
 CREATE TABLE Tratamiento_Aplicado (ID_TRATAMIENTO INT AUTO_INCREMENT , NOMBRE_TRATAMIENTO VARCHAR(200), 
 EFECTIVIDAD_TRATAMIENTO INT,
 PRIMARY KEY (ID_TRATAMIENTO)
 );
 INSERT INTO Tratamiento_Aplicado (NOMBRE_TRATAMIENTO,EFECTIVIDAD_TRATAMIENTO)
 SELECT DISTINCT TemporalR1.TRATAMIENTO ,TemporalR1.EFECTIVIDAD
 FROM TemporalR1;
 USE Practica_MIA;
/*
ESTADO DEL PACIENTE
*/
CREATE TABLE Desc_Paciente ( ID_ESTADO INT AUTO_INCREMENT ,DESCP_ESTADO_PACIENTE VARCHAR(200)
, PRIMARY KEY (ID_ESTADO));
 INSERT INTO Desc_Paciente (DESCP_ESTADO_PACIENTE)
 SELECT DISTINCT ESTADO_VICTIMA 
 FROM TemporalR1
 WHERE ESTADO_VICTIMA NOT IN (SELECT DESCP_ESTADO_PACIENTE FROM Desc_Paciente) 
 AND TemporalR1.ESTADO_VICTIMA!="" OR TemporalR1.ESTADO_VICTIMA!=NULL ;
 /*
 ASOCIADO 
 */
  CREATE TABLE DESC_ASOCIADO (ID_ASOCIADO INT AUTO_INCREMENT,  NOMBRE_ASOCIADO VARCHAR(200), APELLIDO_ASOCIADO VARCHAR(200)
 , PRIMARY KEY (ID_ASOCIADO));
  INSERT INTO DESC_ASOCIADO (NOMBRE_ASOCIADO, APELLIDO_ASOCIADO)
  SELECT DISTINCT TemporalR1.NOMBRE_ASOCIADO , TemporalR1.APELLIDO_ASOCIADO FROM TemporalR1;
 
/*
DESC_CONTACTO 
*/
CREATE TABLE DESC_CONTACTO (ID_CONTACTO INT AUTO_INCREMENT , DESC_CONTACT VARCHAR(200) ,
PRIMARY KEY(ID_CONTACTO));
INSERT INTO DESC_CONTACTO (DESC_CONTACT) SELECT DISTINCT TemporalR1.CONTACTO_FISICO FROM TemporalR1;


/*
LUGARES_VISITADOS

*/
CREATE TABLE LUGARES_VISITADOS (ID_LUGAR INT AUTO_INCREMENT , LUGAR VARCHAR(200), 
PRIMARY KEY (ID_LUGAR));
INSERT INTO LUGARES_VISITADOS (LUCHAR) SELECT DISTINCT TemporalR1.UBICACION_VICTIMA FROM TemporalR1;
/**

VISTIMA



*/
#PRIMERO SE CREA LA TABLA

CREATE TABLE VISTIMA (ID_VISTIMA INT AUTO_INCREMENT , NOMBRE_VISTIMA VARCHAR(200), APELLIDO_VISTIMA VARCHAR(200),
DIRECCION_VISTIMA VARCHAR(200),
FECHA_SOSPECHA VARCHAR(200), MUERTE VARCHAR(200)  , CONFIRMACION VARCHAR(200), ID_ESTADO_P INT,
PRIMARY KEY (ID_VISTIMA),

FOREIGN KEY(ID_ESTADO_P) references Desc_Paciente(ID_ESTADO)
);

INSERT INTO VISTIMA (NOMBRE_VISTIMA,APELLIDO_VISTIMA,DIRECCION_VISTIMA,FECHA_SOSPECHA,MUERTE,CONFIRMACION,
ID_ESTADO_P) SELECT DISTINCT NOMBRE_VICTIMA,APELLIDO_VICTIMA,DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,FECHA_MUERTE,FECHA_CONFIRMACION,ID_ESTADO
from TemporalR1,Desc_Paciente
WHERE  ESTADO_VICTIMA=Desc_Paciente.DESCP_ESTADO_PACIENTE
AND NOMBRE_VICTIMA!='' OR NOMBRE_VICTIMA!=NULL;


/**
 DEFINICION TRATAMIENTO

 
*/


CREATE TABLE DEF_TRATAMIENTO ( TRATAMIENTO_id INT AUTO_INCREMENT ,  HOSPITAL_id INT, ID_TRATAMIENTO_APLICADO INT,
EFECTIVIDAD_VISTIMA INT,VISTIMA_ID INT ,PRIMARY KEY(TRATAMIENTO_id),FOREIGN KEY (HOSPITAL_id) 
REFERENCES HOSPITAL_COVID(ID_HOSPITAL),
FOREIGN KEY (ID_TRATAMIENTO_APLICADO) REFERENCES Tratamiento_Aplicado (ID_TRATAMIENTO),
FOREIGN KEY (VISTIMA_ID) REFERENCES VISTIMA (ID_VISTIMA)

); 

INSERT INTO DEF_TRATAMIENTO(HOSPITAL_id,ID_TRATAMIENTO_APLICADO,EFECTIVIDAD_VISTIMA,VISTIMA_ID)
SELECT DISTINCT ID_HOSPITAL,ID_TRATAMIENTO, TemporalR.EFECTIVIDAD_EN_VICTIMA,ID_VISTIMA FROM
TemporalR,HOSPITAL_COVID,Tratamiento_Aplicado,VISTIMA
WHERE TemporalR.NOMBRE_HOSPITAL=NOMBRE__HOSPITAL AND TemporalR.NOMBRE_VICTIMA=NOMBRE_VISTIMA
AND NOMBRE_TRATAMIENTO=TemporalR.TRATAMIENTO AND TemporalR.APELLIDO_VICTIMA=APELLIDO_VISTIMA
AND TemporalR.DIRECCION_VICTIMA=DIRECCION_VISTIMA AND TemporalR.DIRECCION_HOSPITAL=DIRECCION__HOSPITAL
 ;/**
 CREACION E INSERCION DE LA TABLA VISITA
 
 */
 
CREATE TABLE  VISITAS (
 ID_VISITA INT AUTO_INCREMENT , LLEGADA DATETIME , SALIDA DATETIME, VISTIMA_IDS INT, UBICACION_ID
 INT , PRIMARY KEY (ID_VISITA), foreign key (VISTIMA_IDS) references VISTIMA(ID_VISTIMA)
 ,foreign key (UBICACION_ID) references LUGARES_VISITADOS(ID_LUGAR)
 );
 
USE Practica_MIA;
  INSERT INTO VISITAS(LLEGADA,SALIDA,VISTIMA_IDS,UBICACION_ID) SELECT DISTINCT TemporalR.FECHA_LLEGADA
 ,TemporalR.FECHA_RETIRO,ID_VISTIMA,ID_LUGAR FROM TemporalR,VISTIMA,LUGARES_VISITADOS
 WHERE TemporalR.NOMBRE_VICTIMA=NOMBRE_VISTIMA AND LUGAR=TemporalR.UBICACION_VICTIMA 
 AND TemporalR.APELLIDO_VICTIMA=APELLIDO_VISTIMA AND TemporalR.DIRECCION_VICTIMA=DIRECCION_VISTIMA;


/**
contactos

*/
 CREATE TABLE CONTACTO (ID_CONTACT INT auto_increment ,INICIO DATETIME,FIN DATETIME,
VISTIMA__ID INT,DESC_CONTACTO_ID INT, DESC_ASOCIADO_ID INT ,
PRIMARY KEY (ID_CONTACT), foreign key(VISTIMA__ID) references VISTIMA(ID_VISTIMA),
foreign key (DESC_CONTACTO_ID ) references DESC_CONTACTO(ID_CONTACTO),
foreign key(DESC_ASOCIADO_ID)references DESC_ASOCIADO (ID_ASOCIADO)

);
 
INSERT INTO CONTACTO (INICIO,FIN,VISTIMA__ID,DESC_CONTACTO_ID,DESC_ASOCIADO_ID)
SELECT distinct TemporalR.FECHA_INICIO_CONTACTO, TemporalR.FECHA_FIN_CONTACTO,ID_VISTIMA,
ID_CONTACTO,ID_ASOCIADO
FROM TemporalR,DESC_ASOCIADO,DESC_CONTACTO,VISTIMA
 WHERE TemporalR.NOMBRE_VICTIMA=NOMBRE_VISTIMA AND TemporalR.CONTACTO_FISICO=DESC_CONTACT
 AND TemporalR.NOMBRE_ASOCIADO=NOMBRE_INVOLUCRADO AND TemporalR.APELLIDO_VICTIMA =APELLIDO_VISTIMA
 AND TemporalR.APELLIDO_ASOCIADO=APELLIDO_INVOLUCRADO AND TemporalR.DIRECCION_VICTIMA=DIRECCION_VISTIMA;

;