/*
sql de consulta de pruebas

Error Code: 1136. Column count doesn't match value count at row 1

*/




/* 
CREATE TABLE DEF_TRATAMIENTO ( TRATAMIENTO_id INT AUTO_INCREMENT ,  HOSPITAL_id INT, ID_TRATAMIENTO_APLICADO INT,
EFECTIVIDAD_VISTIMA INT,VISTIMA_ID INT ,PRIMARY KEY(TRATAMIENTO_id),FOREIGN KEY (HOSPITAL_id) 
REFERENCES HOSPITAL_COVID(ID_HOSPITAL),
FOREIGN KEY (ID_TRATAMIENTO_APLICADO) REFERENCES Tratamiento_Aplicado (ID_TRATAMIENTO),
FOREIGN KEY (VISTIMA_ID) REFERENCES VISTIMA (ID_VISTIMA)

); 
/*
INSERT INTO VISTIMA (NOMBRE_VISTIMA,APELLIDO_VISTIMA,DIRECCION_VISTIMA,FECHA_SOSPECHA,MUERTE,CONFIRMACION,
ID_ESTADO_P) SELECT DISTINCT NOMBRE_VICTIMA,APELLIDO_VICTIMA,DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,FECHA_MUERTE,FECHA_CONFIRMACION,ID_ESTADO
from TemporalR1,Desc_Paciente
WHERE  ESTADO_VICTIMA=Desc_Paciente.DESCP_ESTADO_PACIENTE
AND (NOMBRE_VICTIMA,APELLIDO_VICTIMA) NOT IN (SELECT NOMBRE_VISTIMA, APELLIDO_VISTIMA FROM VISTIMA)
AND NOMBRE_VICTIMA!='' OR NOMBRE_VICTIMA!=NULL;
*/
/*
INSERT INTO VISTIMA (NOMBRE_VISTIMA,APELLIDO_VISTIMA,DIRECCION_VISTIMA,FECHA_SOSPECHA,MUERTE,CONFIRMACION,
ID_ESTADO_P) SELECT DISTINCT NOMBRE_VICTIMA,APELLIDO_ASOCIADO,DIRECCION_VICTIMA,
FECHA_PRIMERA_SOSPECHA,FECHA_MUERTE,FECHA_CONFIRMACION,ID_ESTADO
from TemporalR1,Desc_Paciente
WHERE  ESTADO_VICTIMA=Desc_Paciente.DESCP_ESTADO_PACIENTE
AND (NOMBRE_VICTIMA,APELLIDO_VICTIMA) NOT IN (SELECT NOMBRE_VISTIMA, APELLIDO_VISTIMA FROM VISTIMA)
AND NOMBRE_VICTIMA!='' OR NOMBRE_VICTIMA!=NULL;

/*
INSERT INTO VISTIMA (NOMBRE_VISTIMA,APELLIDO_VISTIMA,DIRECCION_VISTIMA,FECHA_SOSPECHA,MUERTE,ID_HOSPITAL_,
ID_ESTADO_P) SELECT DISTINCT TemporalR1.NOMBRE_VICTIMA,TemporalR1.APELLIDO_ASOCIADO,TemporalR1.DIRECCION_VICTIMA,
TemporalR1.FECHA_PRIMERA_SOSPECHA,HOSPITAL_COVID.ID_HOSPITAL,Desc_Paciente.ID_ESTADO
from TemporalR1,Desc_Paciente,HOSPITAL_COVID
WHERE TemporalR1.NOMBRE_HOSPITAL=HOSPITAL_COVID.NOMBRE_HOSPITAL 
AND TemporalR1.ESTADO_VICTIMA=Desc_Paciente.DESCP_ESTADO_PACIENTE
*/
 